import { PUBLIC_CDN_URL } from '$env/static/public';

export const iconMap: Record<string, string> = {
	html5: `${PUBLIC_CDN_URL}/icons/html5.svg`,
	css: `${PUBLIC_CDN_URL}/icons/css.svg`,
	javascript: `${PUBLIC_CDN_URL}/icons/javascript.svg`,
	typescript: `${PUBLIC_CDN_URL}/icons/typescript.svg`,
	svelte: `${PUBLIC_CDN_URL}/icons/svelte.svg`,
	vuedotjs: `${PUBLIC_CDN_URL}/icons/vuedotjs.svg`,
	tailwindcss: `${PUBLIC_CDN_URL}/icons/tailwindcss.svg`,
	flutter: `${PUBLIC_CDN_URL}/icons/flutter.svg`,
	nodedotjs: `${PUBLIC_CDN_URL}/icons/nodedotjs.svg`,
	python: `${PUBLIC_CDN_URL}/icons/python.svg`,
	express: `${PUBLIC_CDN_URL}/icons/express.svg`,
	fastapi: `${PUBLIC_CDN_URL}/icons/fastapi.svg`,
	rest: `${PUBLIC_CDN_URL}/icons/rest.svg`,
	graphql: `${PUBLIC_CDN_URL}/icons/graphql.svg`,
	postgresql: `${PUBLIC_CDN_URL}/icons/postgresql.svg`,
	redis: `${PUBLIC_CDN_URL}/icons/redis.svg`,
	mongodb: `${PUBLIC_CDN_URL}/icons/mongodb.svg`,
	sqlite: `${PUBLIC_CDN_URL}/icons/sqlite.svg`,
	docker: `${PUBLIC_CDN_URL}/icons/docker.svg`,
	githubactions: `${PUBLIC_CDN_URL}/icons/githubactions.svg`,
	aws: `${PUBLIC_CDN_URL}/icons/aws.svg`,
	googlecloud: `${PUBLIC_CDN_URL}/icons/googlecloud.svg`,
	railway: `${PUBLIC_CDN_URL}/icons/railway.svg`,
	cloudflare: `${PUBLIC_CDN_URL}/icons/cloudflare.svg`,
	facebook: `${PUBLIC_CDN_URL}/icons/facebook.svg`,
	discord: `${PUBLIC_CDN_URL}/icons/discord.svg`,
	github: `${PUBLIC_CDN_URL}/icons/github.svg`,
	linkedin: `${PUBLIC_CDN_URL}/icons/linkedin.svg`,
	mail: `${PUBLIC_CDN_URL}/icons/mail.svg`,
	location: `${PUBLIC_CDN_URL}/icons/location.svg`,
	link: `${PUBLIC_CDN_URL}/icons/link.svg`,
	x: `${PUBLIC_CDN_URL}/icons/x.svg`
};
